# Generated by Django 4.2 on 2026-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
